{ pkgs, ... } :

{
  imports = [
    ./git.nix
  ];

  home = {
    username = "oldworldboa";
    homeDirectory = "/home/oldworldboa";
    stateVersion = "25.11";
    packages = [
      pkgs.librewolf-bin
      pkgs.hyprlauncher
    ];
  };

  programs = {
    home-manager.enable = true;
    kitty.enable = true;
  };

  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    systemd.enable = true;

    settings = {
      autogenerated = 0;
      "$mod" = "SUPER";
      "$terminal" = "kitty";
      "$browser" = "librewolf";
      "$launcher" = "hyprlauncher";

      exec-once = [
        "$terminal"
      ];

      bind = [
        "$mod, M, exit,"
        "$mod, C, killactive,"
        "$mod, Q, exec, $terminal"
        "$mod, B, exec, $browser"
        "$mod, R, exec, $launcher"
      ];
    };
  };
}
