
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  imports = [inputs.hyprland.nixosModules.default];

  programs.hyprland = {
    enable = true;
    withUWSM = true;

    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
    plugins = [
      pkgs.hyprlandPlugins.hyprtrails
    ];
    settings = {
      "$terminal" = "kitty";
      "$chat" = "discord";
      exec-once = [
        "$terminal"
        "$chat"
      ];
    };
    extraConfig = ''
      autogenerated=0
    '';
  };
}

