
{ config, lib, pkgs, inputs, ... }:

{
  imports = [
    ./default-style.nix
    ./keybinds.nix
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    systemd.enable = true;

    settings = {
      autogenerated = 0;

      ###########
      # DEVICES #
      ###########
      monitor = ",preferred,auto,auto";
      windowrule = [
        "match:class .*, suppress_event maximize"
	"match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen: false, match:pin false, no_focus on"
      ];


      ###########
      # Layouts #
      ###########

      dwindle = {
        pseudotile = true;
	preserve_split = true;
      };

      master = {
        new_status = "inherit";
      };

      ########
      # Misc #
      ########

      misc = {
        disable_hyprland_logo = true;
	force_default_wallpaper = 0;
      };
    };
  };
}

