
{ config, lib, pkgs, ... }:

{
  imports = [
    ./default-style.nix
    ./keybinds.nix
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    systemd.enable = true;

    settings = {
      autogenerated = 0;

      ###########
      # DEVICES #
      ###########
      monitor = ",preferred,auto,auto";

      ###########
      # Layouts #
      ###########

      dwindle = {
        pseudotile = true;
	preserve_split = true;
      };

      master = {
        new_status = "inherit";
      };

      ########
      # Misc #
      ########

      misc = {
        disable_hyprland_logo = true;
	force_default_wallpaper = 0;
      };
    };
  };
}

