
{ config, lib, pkgs, inputs, ... }:

{
  imports = [
    inputs.hyprland.homeManagerModules.default
    ./default-style.nix
    ./keybinds.nix
    ./waybar.nix
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = true;

    plugins = [
    ];

    settings = {
      autogenerated = 0;

      ###########
      # DEVICES #
      ###########
      monitor = "HDMI-A-5,preferred,auto,auto";

      workspace = [
        "1, monitor:HDMI-A-5"
        "2, monitor:HDMI-A-5"
        "3, monitor:HDMI-A-5"
        "4, monitor:HDMI-A-5"
        "5, monitor:HDMI-A-5"
        "6, monitor:DP-4"
        "7, monitor:DP-4"
        "8, monitor:DP-4"
        "9, monitor:DP-4"
      ];

      windowrule = [
        "workspace 1, match:class kitty"
        "workspace 2, match:class librewolf"
        "match:class .*, suppress_event maximize"
	"match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on"
      ];


      ###########
      # Layouts #
      ###########

      dwindle = {
        pseudotile = true;
	preserve_split = true;
      };

      master = {
        new_status = "inherit";
      };

      ########
      # Misc #
      ########

      misc = {
        disable_hyprland_logo = true;
	force_default_wallpaper = 0;
      };
    };
  };
}

